name: Tests

on:
    push:
        branches: [ "main" ]
        paths-ignore:
            - '**.md'
    pull_request:
        branches: [ "main" ]
        paths-ignore:
            - '**.md'
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Install deep-apply
                run: |
                    pip install .

            -   name: Install test dependencies
                run: |
                    pip install -r requirements-test.txt

            -   name: Run tests
                run: |
                    pytest tests
